name: CD Pipeline
# Only trigger, when the build workflow succeeded i.e. CI Pipeline
on:
workflow_run:
workflows: ["CI Pipeline"]
types:
  - completed
jobs:
deploy:
runs-on: self-hosted
steps:
- name: Pull Docker Image
  env:
  DOCKER_USER: ${{ secrets.DOCKER_USER_NAME }}
  run: sudo docker pull $DOCKER_USER/bikeshare-api:latest
- name: Delete Old Docker Container
  run: sudo docker rm -f bikeshare-api-container || true
- name: Run Docker Container
  env:
  DOCKER_USER: ${{ secrets.DOCKER_USER_NAME }}
  run: sudo docker run -it -d -p 8001:8001 --name 
bikeshare-api-container $DOCKER_USER/bikeshare-api:latest
name: CD Pipeline

# Only trigger, when the build workflow succeeded i.e. CI Pipeline
on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull Docker Image
        env: 
          DOCKER_USER: ${{ secrets.DOCKER_USER_NAME }}
        run: sudo docker pull $DOCKER_USER/bikesharing-fastapi:latest

      - name: Stop Old Docker Container (if running)
        run: sudo docker stop bikesharing-fastapi-container || true

      - name: Delete Old Docker Container
        run: sudo docker rm bikesharing-fastapi-container || true
    
      - name: Run Docker Container
        env: 
          DOCKER_USER: ${{ secrets.DOCKER_USER_NAME }}
        run: sudo docker run -it -d --restart=always -p 8001:8001 --name bikesharing-fastapi-container $DOCKER_USER/bikesharing-fastapi:latest